on:
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"
jobs:
  release:
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.15
      BUILD_OS: ${{ matrix.os.name }}
      CONFIGURATION: ${{ matrix.configuration }}
      SUDO: ${{ matrix.os.name != 'windows' && 'sudo' || ''}}
    strategy:
      fail-fast: false
      matrix:
        os:
        - name: macos
          suffix: '-intel'
          version: 12
          path-separator: ':'
          path-join: '/'
          flag: 'x86_64'
        - name: macos
          suffix: '-silicon'
          version: 14
          path-separator: ':'
          path-join: '/'
          flag: 'arm64'
        - name: ubuntu
          suffix: ''
          version: 22.04
          path-separator: ':'
          path-join: '/'
        - name: windows
          suffix: ''
          version: 2022
          path-separator: ';'
          path-join: '\'
        boost-version:
        - 1.85.0
        sfml-version:
        - 2.6.1
        configuration:
        - Release
        - Debug
    runs-on: '${{ matrix.os.name }}-${{ matrix.os.version }}'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # ZLIB
      - name: CMake zlib for linux
        run: cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=../ -S . -B build
        working-directory: zlib
        if: ${{ matrix.os.name == 'ubuntu' }}
      - name: CMake zlib for windows
        run: cmake -DCMAKE_INSTALL_PREFIX=../ -S . -B build -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
        working-directory: zlib
        if: ${{ matrix.os.name == 'windows' }}
      - name: Build zlib for linux
        run: make && make install
        working-directory: zlib/build
        if: ${{ matrix.os.name == 'ubuntu' }}
      - name: Build zlib for windows
        run: './.github/workflows/scripts/win/zlib-build.bat x64 ${{matrix.configuration}}'
        if: ${{ matrix.os.name == 'windows' }}
      - name: Copy zlib includes for windows
        run: |
          mkdir -p include/examples && \
            mkdir -p include/contrib && \
            cp zlib/*.h include/ && \
            cp zlib/zconf.h.included include/zconf.h && \
            cp zlib/examples/*.h include/examples && \
            cp -r zlib/contrib/** include/contrib/
        shell: bash
        if: ${{ matrix.os.name == 'windows' }}
      - name: Copy zlib for windows
        run: 'mkdir -p lib && cp zlib/build/${{matrix.configuration}}/* lib/'
        shell: bash
        if: ${{ matrix.os.name == 'windows' }}

      # SFML
      - name: Build SFML
        id: sfml
        uses: NQNStudios/install-sfml@v1
        with:
          sfml: ${{ matrix.sfml-version }}
          config: ${{ matrix.configuration }}
          arch: ${{ matrix.os.flag || '' }}

      - run: cp bin/*.dll lib/
        shell: bash
        if: ${{ matrix.os.name == 'windows' }}

      - run: mkdir -p include && mkdir -p lib
        if: ${{ matrix.os.name == 'macos' }}

      # BOOST
      # the original build-boost action maintainer has gone awol
      # - my fork incorporates required changes
      - name: Build Boost (fork)
        id: boost-fork
        uses: NQNStudios/build-boost@v1.0.2
        with:
          version: ${{ matrix.boost-version }}
          libraries: filesystem system locale
          platform: x64
          configuration: ${{ matrix.configuration }}
          static: ${{ matrix.os.name == 'windows' }}
          extra-flag: ${{ matrix.os.name == 'macos' && '--break-system-packages' || '' }}
      - name: Copy boost include to output folders
        run: $SUDO cp -r '${{ steps.boost-fork.outputs.root }}${{ matrix.os.path-join }}boost' include/
        shell: bash
      - name: Copy boost libs to output folders
        run: $SUDO cp -r '${{ steps.boost-fork.outputs.librarydir }}${{ matrix.os.path-join }}'""* lib/
        if: ${{ matrix.os.name != 'windows' }}
      # weird workaround
      - run: rm -rf lib/cmake
        shell: bash
        if: ${{ matrix.os.name == 'windows' }}
      - name: Copy boost libs to output folders (windows)
        run: copy '${{steps.boost-fork.outputs.librarydir }}${{ matrix.os.path-join }}*' lib/
        if: ${{ matrix.os.name == 'windows' }}

      - name: 'Tar files'
        run: 'tar -cvf dependencies-${{ matrix.os.name }}${{matrix.os.suffix}}-${{ matrix.configuration }}.tar "include" "lib"'

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: dependencies-${{ matrix.os.name }}${{matrix.os.suffix}}-${{ matrix.configuration }}
          path: dependencies-${{ matrix.os.name }}${{matrix.os.suffix}}-${{ matrix.configuration }}.tar
      - name: Github release
        uses: softprops/action-gh-release@v2
        with:
          files: dependencies-${{ matrix.os.name }}${{matrix.os.suffix}}-${{ matrix.configuration }}.tar
        if: ${{ startsWith(github.ref, 'refs/tags/') }}