name: Mac universal build
on:
  push:
    branches:
      - universal
  release:
    types: [published]
jobs:
  build:
    runs-on: macos-14
    env:
      CONFIGURATION: ${{ matrix.configuration }}
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Release
          - Debug
    steps:
      - uses: actions/checkout@v4

      # Download macos-intel
      - uses: robinraju/release-downloader@v1
        id: download
        with:
          latest: true
          fileName: 'dependencies-macos-intel-${{ matrix.configuration }}.tar'
          extract: true
          out-file-path: 'dependencies-macos-intel-${{ matrix.configuration }}'

      # Download macos-silicon
      - uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: 'dependencies-macos-silicon-${{ matrix.configuration }}.tar'
          extract: true
          out-file-path: 'dependencies-macos-silicon-${{ matrix.configuration }}'

      - run: ./make-universal.sh

      - name: 'Tar files'
        run: 'tar -cvf dependencies-macos-universal-${{matrix.configuration}}.tar "include" "lib"'

      # Upload everything as artifact
      - uses: actions/upload-artifact@v4
        with:
          name: mac-universal-dependencies-${{matrix.configuration}}
          path: dependencies-macos-universal-${{matrix.configuration}}.tar

      # upload a release
      - name: Github release
        uses: softprops/action-gh-release@v2
        with:
          files: dependencies-macos-universal-${{ matrix.configuration }}.tar
          tag_name: ${{ steps.download.outputs.tag_name }}